package pl.mkrew.backend.dto;

import jakarta.validation.constraints.Email;
import jakarta.validation.constraints.NotBlank;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class LoginRequest {

    @NotBlank(message = "Email is required")
    @Email(message = "Email must be valid")
    private String email;

    @NotBlank(message = "Password is required")
    private String password;

    /**
     * reCAPTCHA token (optional - required only after 3 failed login attempts)
     * Generated by Google reCAPTCHA v2 widget on frontend
     * Verified against Google reCAPTCHA API
     */
    private String captchaToken;
}
