FROM liquibase/liquibase:4.25-alpine

# PostgreSQL JDBC driver jest już wbudowany w oficjalnym obrazie
WORKDIR /liquibase

# Katalog changelog będzie montowany jako volume w docker-compose
CMD ["--help"]
